### ISSUE TITLE
[MID SCENE in MEETING]: 침 삼키는 소리와 애니메이션의 싱크가 안맞음

### ISSUE THREAD

**Issue by Jae12ho** [Junhyung-Choi/PythonGame#102]
### What happened?

침 삼키는 소리와 애니메이션의 싱크가 안맞음

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
screen.blit 이후에 사운드가 출력되도록 조정 가능한지 검토 부탁

**Comment by Jae12ho** [comment]
해결됨
