### ISSUE TITLE
[Script]: Script class의 static method와 관련하여

### ISSUE THREAD

**Issue by peanutyumyum** [Junhyung-Choi/PythonGame#107]
### What happened?

말풍선 나오는 부분 만들고 있는데, Script class를 활용하고자 합니다. 다만, metting에서 class 단위로 사용되고 있어서, 따로 인스턴스 단위로 만들기 힘든 부분이 있습니다.
Script class에서 static method가 사용되는 이유가 있나요?? 

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
static으로 사용시 인스턴스를 선언 및 초기화 하지 않고도 클래스 내부의 변수들을 활용 가능하기 때문에 setting.py에 변수를 종속시키는 것이 아니라 스크립트에 종속시키는 것이 가능해서 그렇게 설계했습니다.
init 함수를 통해 초기화를 진행한다면 다른 방식으로도 사용 가능할 것으로 예상됩니다.
혹은 비슷한 방식으로 다른 static method를 설계해보는 것은 어떤가요?

**Comment by peanutyumyum** [comment]
설계 완료 하였습니다.
