### ISSUE TITLE
[MEETING]: 남은 시간이 0분 0초가 되었을 때 게임오버가 되어야 함.

### ISSUE THREAD

**Issue by Jae12ho** [Junhyung-Choi/PythonGame#108]
### What happened?

남은 시간이 0분 0초가 되었을 때 게임오버가 되어야 함.

### Branch Version

feature/meeting

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peanutyumyum** [comment]
시간이 0이 되는 경우 gameover.py의 active_gameover()를 호출하게끔 완료하였음

엔딩 씬 호출은 해당 부분이 완료되어야 완전하게 돌아갈 것임

**Comment by Junhyung-Choi** [comment]
setting.stage = -1 로 방법 변경해보죠
