### ISSUE TITLE
[Initing]: 전반적인 게임 초기화 함수가 필요함

### ISSUE THREAD

**Issue by Junhyung-Choi** [Junhyung-Choi/PythonGame#127]
### Contact Details

junhyung9571@naver.com

### What happened?

엔딩을 보고 난 후
일시정지를 통한 게임 종료 후 
다시 게임을 플레이 할때 이전 게임 플레이 내용들이 초기화 되지 않는다는 것을 확인함. 
기능 추가가 필요

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
stage = 0으로 바꾸고 나서 다시 stage 변수를 통해서 씬이 돌아올때 
남아있을 수 있는 변수 리스트를 리스트업을 해야 할 것 같음.
settings.py 안에 주로 남아있을 것 같음.

**Comment by Junhyung-Choi** [comment]
10월 6일 4시 이후로 확인

**Comment by peanutyumyum** [comment]
저희 그냥 first 변수 사용해서 핸들링 하는건 어떨까요?? story 같은 경우는 first 변수만 True로 바꿔주면 다시 동작하거든요!

**Comment by Junhyung-Choi** [comment]
#142

**Comment by Junhyung-Choi** [comment]
엔딩 초기화까지 완료
