### ISSUE TITLE
[Middle, Ending]: 이미지 전환 버튼이 필요함

### ISSUE THREAD

**Issue by Junhyung-Choi** [Junhyung-Choi/PythonGame#130]
### Contact Details

junhyung9571@naver.com

### What happened?

다음 페이지로 넘어가는 스킵 버튼이 있으면 좋겠다는 이야기를 들음.

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
자동 전환 기능 삭제 추가 요청

**Comment by Jae12ho** [comment]
작업완료
