### ISSUE TITLE
[Credit]: 엔딩 끝나고 나오면 나와야 함.  

### ISSUE THREAD

**Issue by Junhyung-Choi** [Junhyung-Choi/PythonGame#155]
### What happened?

![image](https://user-images.githubusercontent.com/50592308/194283572-66bc95f3-3f57-42a4-ae9c-6cf524278708.png)

이미지 나와야 함

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jae12ho** [comment]
만들었음.
