### ISSUE TITLE
[Middle, Sound.]: 페이즈 전환씬으로 진입할 때 배경음악 멈췄다가 끝난 후 다시 재생

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#174]
### What happened?

긴장감이 도는 씬에서 편안한 재즈가 나오면 긴장감이 많이 낮아짐. 그래서 잠깐 멈췄다가 재생되는게 좋을 것 같음.

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jae12ho** [comment]
중간에 볼륨 줄였다가 다시 키우는 것으로 수정.
