### ISSUE TITLE
[Game Scene]: 창문 배경이 살짝 우측으로 옮겨졌으면 좋겠음

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#55]
### What happened?

창문 배경이 너무 좌측에 붙어있다는 생각이 들어 우측으로 옮기면 좋겠음

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
안옮기기로 함
