### ISSUE TITLE
[Game Scene]: 미소짓는 모션을 몇초동안 (2~3초 정도로 계속 웃을 수 있도록 조절)

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#58]
### What happened?

미소짓는 모션을 잠깐이 아닌 좀 더 길게 하도록 조절 (2~3초)

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
프레임 수 늘려서 해결
