### ISSUE TITLE
[Game Scene]: 손 테이블에 올렸다가 내리는 모션을 현재 호감도 수치가 어떤지 알려주는 애니메이션으로 변경

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#60]
### What happened?

손 테이블에 올렸다가 내리는 모션을 현재 호감도 수치가 어떤지 알려주는 애니메이션으로 변경

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
불가.
