### ISSUE TITLE
[Game Scene]: 핸드폰 이벤트 애니메이션 추가 (중간 점검 이벤트 씬임을 표시)

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#61]
### What happened?

1페이즈 끝나고 나서 중간점검 이벤트 씬 하나 넣기. 현재 호감도 수치에 따라 이벤트 씬이 달라짐. 

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
애니메이션은 적용 완료
중간 씬 적용되면 이슈 닫아주세요 @Jae12ho
