### ISSUE TITLE
[Game Scene]: 효과음, 배경음이 없음

### ISSUE THREAD

**Issue by RagSpirin** [Junhyung-Choi/PythonGame#65]
### What happened?

게임에 사용될 효과음과 배경음이 없음 추가해야함.

### Branch Version

overall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
- 컷씬 효과음 필요함 (스토리 씬 / 중간점검 씬 / 엔딩 씬)
- 배경음악 필요함 ( 메뉴 씬 / 미팅 씬 )

**Comment by Jae12ho** [comment]
스토리 씬 효과음 작업 완료

**Comment by Junhyung-Choi** [comment]
메뉴 씬 배경음악 적용완료
