### ISSUE TITLE
[MEETING SCENE]: 미들 씬 넘어가기 전 말풍선 렌더링 안되게 해야함

### ISSUE THREAD

**Issue by Jae12ho** [Junhyung-Choi/PythonGame#88]
### What happened?

미들 씬 넘어가기 직전에 말풍선이 먼저 2라운드의 내용으로 업데이트가 됨.
유저 입장에서 1라운드가 아직 안 끝났는데 미들 씬이 나온다고 생각할 수 있음.

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
#91
