### ISSUE TITLE
[SCORE SYSTEM]: 기본 점수 제안

### ISSUE THREAD

**Issue by Jae12ho** [Junhyung-Choi/PythonGame#92]
### What happened?

기본 점수 :15
점수 증감폭 : -3~+3
라고 가정하면,

질문 횟수 : 1라운드 3회 + 2라운드 3회
총 6회의 횟수로 나올 수 있는 
최악의 점수는 15 - 3 * 6 = -3
최고의 점수는 15 + 3 * 6 = 33
이므로, 

기준 점수
0~7 (최악), 29 이상 (최고)
를 고려했을 때 기본 점수 15점은 가장 이상적인 기본 점수라고 생각됨.

### Branch Version

develop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Junhyung-Choi** [comment]
15로 변경 ㄱㄱ

**Comment by Junhyung-Choi** [comment]
#96
